add image of titanic in readme.md

# Loading and Taking Insigths of Dataset

## Loading the dataset

In [4]:
# Essential imports
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [5]:
# uploading the dataset
# check the readme file to know about the source of dataset
from google.colab import files
uploaded = files.upload()

Saving test.csv to test (1).csv
Saving train.csv to train (1).csv


In [6]:
# Loading the dataset
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

## Taking insigths of dataset

In [7]:
# How our dataset looks like
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
# PasengerId can be the index of the dataset
train_data.set_index("PassengerId", inplace=True)
test_data.set_index("PassengerId", inplace=True)

In [9]:
train_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [10]:
# about our dataset
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Ticket    891 non-null    object 
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object 
 10  Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB


In [11]:
# about the data of the dataset
train_data.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [12]:
# how many having no fare
# you can see that out of all only 1 survived whose fare is 0
train_data[train_data['Fare']==0]

Survived  Pclass                              Name   Sex   Age  \
PassengerId                                                                   
180                 0       3               Leonard, Mr. Lionel  male  36.0   
264                 0       1             Harrison, Mr. William  male  40.0   
272                 1       3      Tornquist, Mr. William Henry  male  25.0   
278                 0       2       Parkes, Mr. Francis "Frank"  male   NaN   
303                 0       3   Johnson, Mr. William Cahoone Jr  male  19.0   
414                 0       2    Cunningham, Mr. Alfred Fleming  male   NaN   
467                 0       2             Campbell, Mr. William  male   NaN   
482                 0       2  Frost, Mr. Anthony Wood "Archie"  male   NaN   
598                 0       3               Johnson, Mr. Alfred  male  49.0   
634                 0       1     Parr, Mr. William Henry Marsh  male   NaN   
675                 0       2        Watson, Mr. Ennis Hastings  male   NaN   
733                 0       2              Knight, Mr. Robert J  male   NaN   
807                 0       1            Andrews, Mr. Thomas Jr  male  39.0   
816                 0       1                  Fry, Mr. Richard  male   NaN   
823                 0       1   Reuchlin, Jonkheer. John George  male  38.0   

             SibSp  Parch  Ticket  Fare Cabin Embarked  
PassengerId                                             
180              0      0    LINE   0.0   NaN        S  
264              0      0  112059   0.0   B94        S  
272              0      0    LINE   0.0   NaN        S  
278              0      0  239853   0.0   NaN        S  
303              0      0    LINE   0.0   NaN        S  
414              0      0  239853   0.0   NaN        S  
467              0      0  239853   0.0   NaN        S  
482              0      0  239854   0.0   NaN        S  
598              0      0    LINE   0.0   NaN        S  
634              0      0  112052   0.0   NaN        S  
675              0      0  239856   0.0   NaN        S  
733              0      0  239855   0.0   NaN        S  
807              0      0  112050   0.0   A36        S  
816              0      0  112058   0.0  B102        S  
823              0      0   19972   0.0   NaN        S

In [13]:
len(train_data[train_data['Survived']==1])

342

In [14]:
# No of survivals
train_data['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [15]:
train_data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [16]:
# How many males and females
train_data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [17]:
train_data['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

# Processing tha dataset to fit in the model

In [18]:
# Pipelines makes the process simple and are very handy to use
from sklearn.pipeline import Pipeline
# To deal with the null values
from sklearn.impute import SimpleImputer
# To scale the data to the unit variance
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
                         ('imputer', SimpleImputer(strategy='median')),
                         ('scaler', StandardScaler())
                         ])

In [19]:
# OneHotEncoder converts the characters of column to numbers
from sklearn.preprocessing import OneHotEncoder

In [20]:
# Creating Pipeline
cat_pipeline = Pipeline([
                         ('imputer', SimpleImputer(strategy='most_frequent')),
                         ('cat_encoder', OneHotEncoder(sparse=False))
])

In [21]:
# Apply separate transformer for numerical and categorical data
from sklearn.compose import ColumnTransformer

In [22]:
# Numerical data columns
num_attribs = ['Age', 'SibSp', 'Parch', 'Fare']
# Categorical data columns
cat_attribs = ['Pclass', 'Sex', 'Embarked']

preprocess_pipeline = ColumnTransformer([
                                         ('num', num_pipeline, num_attribs),
                                         ('cat', cat_pipeline, cat_attribs),
])

In [23]:
X_train = preprocess_pipeline.fit_transform(
    train_data[num_attribs + cat_attribs])

# What our data looks like after processing it
X_train

array([[-0.56573646,  0.43279337, -0.47367361, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.66386103,  0.43279337, -0.47367361, ...,  1.        ,
         0.        ,  0.        ],
       [-0.25833709, -0.4745452 , -0.47367361, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-0.1046374 ,  0.43279337,  2.00893337, ...,  0.        ,
         0.        ,  1.        ],
       [-0.25833709, -0.4745452 , -0.47367361, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.20276197, -0.4745452 , -0.47367361, ...,  0.        ,
         1.        ,  0.        ]])

In [24]:
X_train[0]

array([-0.56573646,  0.43279337, -0.47367361, -0.50244517,  0.        ,
        0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ])

In [25]:
# Taking labels
y_train = train_data['Survived']

# Training Different Models

## Training Random Forest Classifier

In [26]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(n_estimators=100, random_state = 42)
forest_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [27]:
from sklearn.model_selection import cross_val_score

forest_scores = cross_val_score(forest_clf, X_train, y_train, cv=10)
forest_scores


array([0.74444444, 0.79775281, 0.75280899, 0.80898876, 0.87640449,
       0.83146067, 0.83146067, 0.7752809 , 0.83146067, 0.84269663])

In [28]:
forest_scores.mean()

0.8092759051186016

## Training Suppor Vector Machine (SVM)

In [29]:
from sklearn.svm import SVC

svm_clf = SVC(gamma="auto")
svm_clf.fit(X_train, y_train)


SVC(gamma='auto')

In [30]:
svm_scores = cross_val_score(svm_clf, X_train, y_train, cv=10)
svm_scores

array([0.81111111, 0.85393258, 0.7752809 , 0.87640449, 0.83146067,
       0.79775281, 0.82022472, 0.78651685, 0.85393258, 0.84269663])

In [31]:

svm_scores.mean()

0.8249313358302123

## Improve Performance using Feature Engineering

In [32]:
train_data['Age']//15*15

PassengerId
1      15.0
2      30.0
3      15.0
4      30.0
5      30.0
       ... 
887    15.0
888    15.0
889     NaN
890    15.0
891    30.0
Name: Age, Length: 891, dtype: float64

In [33]:
train_data['Age']

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ... 
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

In [34]:
train_data[['Age', 'Survived']].groupby(['Age']).mean()

Survived
Age            
0.42        1.0
0.67        1.0
0.75        1.0
0.83        1.0
0.92        1.0
...         ...
70.00       0.0
70.50       0.0
71.00       0.0
74.00       0.0
80.00       1.0

[88 rows x 1 columns]

In [35]:
train_data['AgeBucket'] = train_data['Age']//15*15
train_data[['AgeBucket', 'Survived']].groupby(['AgeBucket']).mean()

Survived
AgeBucket          
0.0        0.576923
15.0       0.362745
30.0       0.423256
45.0       0.404494
60.0       0.240000
75.0       1.000000

In [36]:
train_data['AgeBucket'].value_counts()

15.0    306
30.0    215
45.0     89
0.0      78
60.0     25
75.0      1
Name: AgeBucket, dtype: int64

In [37]:
train_data['Relatives'] = train_data['SibSp'] + train_data['Parch']

In [38]:
train_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  \
PassengerId                                                           
1                1      0         A/5 21171   7.2500   NaN        S   
2                1      0          PC 17599  71.2833   C85        C   
3                0      0  STON/O2. 3101282   7.9250   NaN        S   
4                1      0            113803  53.1000  C123        S   
5                0      0            373450   8.0500   NaN        S   

             AgeBucket  Relatives  
PassengerId                        
1                 15.0          1  
2                 30.0          1  
3                 15.0          0  
4                 30.0          1  
5                 30.0          0

In [39]:
sample = pd.read_csv('train.csv')
train_data['Cabin'] = sample['Cabin']

In [40]:
train_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  \
PassengerId                                                           
1                1      0         A/5 21171   7.2500   C85        S   
2                1      0          PC 17599  71.2833   NaN        C   
3                0      0  STON/O2. 3101282   7.9250  C123        S   
4                1      0            113803  53.1000   NaN        S   
5                0      0            373450   8.0500   NaN        S   

             AgeBucket  Relatives  
PassengerId                        
1                 15.0          1  
2                 30.0          1  
3                 15.0          0  
4                 30.0          1  
5                 30.0          0

In [41]:
train_data['Cabinet'] = train_data['Cabin'].str[0]

In [42]:
train_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  \
PassengerId                                                           
1                1      0         A/5 21171   7.2500   C85        S   
2                1      0          PC 17599  71.2833   NaN        C   
3                0      0  STON/O2. 3101282   7.9250  C123        S   
4                1      0            113803  53.1000   NaN        S   
5                0      0            373450   8.0500   NaN        S   

             AgeBucket  Relatives Cabinet  
PassengerId                                
1                 15.0          1       C  
2                 30.0          1     NaN  
3                 15.0          0       C  
4                 30.0          1     NaN  
5                 30.0          0     NaN

In [43]:
labels = train_data.pop('Survived')

In [44]:
train_data.head()

Pclass                                               Name  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   

                Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
PassengerId                                                                
1              male  22.0      1      0         A/5 21171   7.2500   C85   
2            female  38.0      1      0          PC 17599  71.2833   NaN   
3            female  26.0      0      0  STON/O2. 3101282   7.9250  C123   
4            female  35.0      1      0            113803  53.1000   NaN   
5              male  35.0      0      0            373450   8.0500   NaN   

            Embarked  AgeBucket  Relatives Cabinet  
PassengerId                                         
1                  S       15.0          1       C  
2                  C       30.0          1     NaN  
3                  S       15.0          0       C  
4                  S       30.0          1     NaN  
5                  S       30.0          0     NaN

## Again creating pipeline with featured data

In [45]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [46]:
num_pipeline = Pipeline([
                         ('imputer', SimpleImputer(strategy='median')),
                         ('scaler', StandardScaler())
])

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
cat_pipeline = Pipeline([
                         ('imputer', SimpleImputer(strategy='most_frequent')),
                         ('cat_encoder', OneHotEncoder(sparse=False))
])

In [49]:
from sklearn.compose import ColumnTransformer

In [50]:
num_attribs = ['Fare', 'Relatives']
cat_attribs = ['AgeBucket', 'Pclass', 'Sex', 'Embarked', 'Cabinet']

In [51]:
preprocess_pipeline = ColumnTransformer([
                                         ('num', num_pipeline, num_attribs),
                                         ('cat', cat_pipeline, cat_attribs)
])

In [52]:
X_train = preprocess_pipeline.fit_transform(train_data[num_attribs + cat_attribs])
X_train

array([[-0.50244517,  0.05915988,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.78684529,  0.05915988,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.48885426, -0.56097483,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.17626324,  1.29942929,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.04438104, -0.56097483,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.49237783, -0.56097483,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [53]:
X_train[0]

array([-0.50244517,  0.05915988,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [54]:
y_train = labels

## Training Random Forest Classifier

In [55]:
from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier()

In [56]:
forest_clf.fit(X_train, y_train)

RandomForestClassifier()

In [57]:
from sklearn.model_selection import cross_val_score
forest_scores = cross_val_score(forest_clf, X_train, y_train, cv=10)
forest_scores

array([0.75555556, 0.82022472, 0.76404494, 0.83146067, 0.84269663,
       0.78651685, 0.78651685, 0.75280899, 0.79775281, 0.80898876])

In [58]:
forest_scores.mean()

0.7946566791510612

### With Grid Search CV

In [59]:
from sklearn.model_selection import GridSearchCV
param_grid = [{'max_depth':[2, 8, 16], 'n_estimators': [64, 128, 256]}]
forest_clff = RandomForestClassifier()
grid_search = GridSearchCV(forest_clff, param_grid, cv=5, verbose=3)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5] END ......max_depth=2, n_estimators=64;, score=0.760 total time=   0.1s
[CV 2/5] END ......max_depth=2, n_estimators=64;, score=0.798 total time=   0.1s
[CV 3/5] END ......max_depth=2, n_estimators=64;, score=0.831 total time=   0.1s
[CV 4/5] END ......max_depth=2, n_estimators=64;, score=0.787 total time=   0.1s
[CV 5/5] END ......max_depth=2, n_estimators=64;, score=0.809 total time=   0.1s
[CV 1/5] END .....max_depth=2, n_estimators=128;, score=0.754 total time=   0.3s
[CV 2/5] END .....max_depth=2, n_estimators=128;, score=0.798 total time=   0.2s
[CV 3/5] END .....max_depth=2, n_estimators=128;, score=0.831 total time=   0.3s
[CV 4/5] END .....max_depth=2, n_estimators=128;, score=0.753 total time=   0.3s
[CV 5/5] END .....max_depth=2, n_estimators=128;, score=0.803 total time=   0.3s
[CV 1/5] END .....max_depth=2, n_estimators=256;, score=0.760 total time=   0.5s
[CV 2/5] END .....max_depth=2, n_estimators=256;,

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid=[{'max_depth': [2, 8, 16],
                          'n_estimators': [64, 128, 256]}],
             verbose=3)

In [60]:
grid_search.best_params_

{'max_depth': 8, 'n_estimators': 64}

In [61]:
forest_clf = RandomForestClassifier(**grid_search.best_params_)



In [62]:
forest_clf.fit(X_train, y_train)
forest_scoress = cross_val_score(svm_clf, X_train, y_train, cv=10)
forest_scoress

array([0.81111111, 0.82022472, 0.7752809 , 0.84269663, 0.79775281,
       0.78651685, 0.79775281, 0.79775281, 0.84269663, 0.79775281])

In [63]:
forest_scoress.mean()

0.8069538077403244

## Training Support Vector Machine (SVM)

In [64]:
from sklearn.svm import SVC
svm_clf = SVC(gamma='auto')

In [65]:
svm_clf.fit(X_train, y_train)

SVC(gamma='auto')

In [66]:
svm_scores = cross_val_score(svm_clf, X_train, y_train, cv=10)
svm_scores

array([0.81111111, 0.82022472, 0.7752809 , 0.84269663, 0.79775281,
       0.78651685, 0.79775281, 0.79775281, 0.84269663, 0.79775281])

In [67]:
svm_scores.mean()

0.8069538077403244

### With Grid Search CV

In [68]:
from sklearn.model_selection import GridSearchCV
param_grid = [{'C':[0.01, 0.5, 0.1, 1, 2, 5, 10, 50, 100, 500, 1000], 'gamma':[0.001, 0.01, 0.1, 1]}]

svm_clf = SVC()
grid_search = GridSearchCV(svm_clf, param_grid, cv=5, verbose=1)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 44 candidates, totalling 220 fits


GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [0.01, 0.5, 0.1, 1, 2, 5, 10, 50, 100, 500,
                                1000],
                          'gamma': [0.001, 0.01, 0.1, 1]}],
             verbose=1)

In [69]:
grid_search.best_params_

{'C': 2, 'gamma': 0.1}

In [70]:
svm_clf = SVC(**grid_search.best_params_)

In [71]:
svm_clf.fit(X_train, y_train)

SVC(C=2, gamma=0.1)

In [72]:
svm_scoress = cross_val_score(svm_clf, X_train, y_train, cv=10)
svm_scoress

array([0.81111111, 0.86516854, 0.76404494, 0.8988764 , 0.84269663,
       0.80898876, 0.80898876, 0.79775281, 0.87640449, 0.85393258])

In [73]:
svm_scoress.mean()

0.832796504369538

## Training Decision Tree Classifier

In [74]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()

In [75]:
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [76]:
tree_scores = cross_val_score(tree_clf, X_train, y_train, cv=10)
tree_scores

array([0.78888889, 0.83146067, 0.7752809 , 0.82022472, 0.8988764 ,
       0.7752809 , 0.78651685, 0.75280899, 0.80898876, 0.84269663])

In [77]:
tree_scores.mean()

0.8081023720349563

## Training KNearestNeighbour Classifier

In [78]:
from sklearn.neighbors import KNeighborsClassifier
k_clf = KNeighborsClassifier()

In [79]:
k_clf.fit(X_train, y_train)

KNeighborsClassifier()

In [80]:
k_scores = cross_val_score(k_clf, X_train, y_train, cv=10)
k_scores

array([0.72222222, 0.78651685, 0.74157303, 0.82022472, 0.86516854,
       0.83146067, 0.86516854, 0.7752809 , 0.80898876, 0.79775281])

In [81]:
k_scores.mean()

0.8014357053682897